# -*- coding: utf-8 -*-
"""
Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QKafbw7-8eDjmb1vR8N1aqMjDUpXQhxu
"""


def linear_search(lst, target):
    for i in range(len(lst)):
        if lst[i] == target:
            return i

    return -1


a = [23, 34, 12, 3, 5654, 2, 13, 456]

print(linear_search(a, 2))


def binary_search(lst, target):
    min = 0
    max = len(lst) - 1

    while min <= max:
        guess = (max + min) // 2

        if lst[guess] == target:
            return guess

        elif lst[guess] < target:
            min = guess + 1
        else:
            max = guess - 1

    return -1


l = [1, 2, 3, 45, 67, 78, 98, 120, 200]

print(binary_search(l, 78))

"""# CODE: 3412

"""

n = 5


def n_times_loop(n):
    while n > 0:
        print(n)
        n -= 1


n_times_loop(n)

n = 5


def n_times_recurse(n):
    if n <= 0:
        return

    print(n)
    n_times_recurse(n - 1)


n_times_recurse(n)
